### ISSUE TITLE
Can't make changes to Scratch.image

### ISSUE THREAD

**Issue by davidferguson** [SoftUmeYa/Pyonkee#2]
I can't seem to edit any of the Squeak code in the Scratch.image file. I can edit it and it works when I run the code in the Squeak application on my computer, but as soon as I build it for iPad, when I open the app it freezes on this screen:
![freeze-screen](https://cloud.githubusercontent.com/assets/13520342/12223579/3f65cdde-b7d3-11e5-97fa-5fffbaf0bd0e.png)
This even happens with something as small as changing the name of a menu (eg, changing "File" to "Test"

What I am doing is as follows:
- Downloaded pyonkee-master from GitHub
- Open **Scratch.image** in Squeak 4.2
- Shift-click *File* menu, *Exit User Mode*
- Click on blank space, *Open*, *Browser*
- *Scratch-UI-Panes*, *ScratchFrameMorph*, *initialization*, *createMenuPanel*
- Change "(File			fileMenu:)" to "(Test			fileMenu:)"
- CMD-S to save, enter initials
- Click on blank space, *Save and Quit*
- Open **Pyonkee.xcodeproj**
- Build and run in simulator
- Pyonkee freezes on screen shown above

Could you please assist me with this? If I don't modify **Scratch.image** then it builds and runs fine.

**Comment by mumez** [comment]
Pyonkee's development image highly uses Objective-C bridge for interacting with ObjC components. 
So, our recommendation is opening/saving Pyonkee image only on Mac OS X. Moreover, please note that Scratch.image requires a slightly older VM. It is not the same as the Squeak 4.2-bundled VM.

We are using Squeak-4.2.2beta1U VM for the development. (The binary is sort of difficult to obtain nowadays, but it is bundled in Squeak3.10.2J-all-in-one.zip.
http://sourceforge.jp/projects/squeak-ja/releases/51524

Hope this helps,
