### ISSUE TITLE
Building without iCloud

### ISSUE THREAD

**Issue by davidferguson** [SoftUmeYa/Pyonkee#4]
This isn't an issue, but rather a note to others who want to experiment with editing Pyonkee without enrolling in Apple's Developer Program which costs money every year:

When attempting to build and run on a physical iPad (not the simulator), you will receive the message:

**The 'iCloud' feature is only available to users enrolled in Apple Developer Program. Please visit  https://developer.apple.com/programs/ to enroll.**

To disable iCloud and allow the build to continue, change [line 2223 of Pyonkee.xcodeproj/project.pbxproj](https://github.com/SoftUmeYa/Pyonkee/Pyonkee.xcodeproj/project.pbxproj#L2223) from:

`enabled = 1;`

to

`enabled = 0;`

which will disable iCloud and allow the build to continue.

You may want to add this to your README to make others aware of this.

**Comment by mumez** [comment]
Thank you for the suggestion. I'll update README soon.

**Comment by mumez** [comment]
I've updated README. Please confirm:
https://github.com/SoftUmeYa/Pyonkee/commit/af390fde1a2d21100bd7e9edeb2238ba58e3b69d

**Comment by davidferguson** [comment]
That looks perfect to me.
