### ISSUE TITLE
german help screen

### ISSUE THREAD

**Issue by aBrAEUMER** [SoftUmeYa/Pyonkee#8]
I would like to provide a german help screen. Which utilities and font did you use to draw the annotations in `help-screen.png` ?

**Comment by mumez** [comment]
We are using Inkscape and "The bold font".
https://inkscape.org
https://www.dafont.com/the-bold-font.font

I've attached English version of the help screen.  It would be a good starting point.
[help-en20180811.zip](https://github.com/SoftUmeYa/Pyonkee/files/1852255/help-en20180811.zip)

**Comment by mumez** [comment]
Resolved by: https://github.com/SoftUmeYa/Pyonkee/pull/7
