### ISSUE TITLE
Creating localized video tutorial

### ISSUE THREAD

**Issue by aBrAEUMER** [SoftUmeYa/Pyonkee#9]
I would like to create a localized video tutorial. It looks like you did a screen recording of pyonkee running in the xcode ipad simulator. How did you make the touch events (mouse clicks) visible? I am aware of helpers like Fingertips or Touchpose but maybe there is a more simple way and I would like to make it look like your tutorial.

**Comment by mumez** [comment]
We have just captured Simulator with QuickTime Player. You can set an option of mouse events feedback.
http://kzoinnovations.com/wp-content/uploads/2013/03/Best-Practice-for-Screen-Recording-with-Quicktime.pdf

**Comment by aBrAEUMER** [comment]
Thanks, this works for me. 
I have created a video (5:19 min) and compressed it to less than 2 MB (using the HandBrake app). Please let me know if you need another resolution, compression or size.
[Pyonkee-Tutorial-DE.mp4.zip](https://github.com/SoftUmeYa/Pyonkee/files/1881902/Pyonkee-Tutorial-DE.mp4.zip)
Is there anything else I could do for a german localization?

**Comment by aBrAEUMER** [comment]
OK, this is a german translation of the english App Store description page.

> 
> Immer nur berieseln lassen? Entdecke den Spaß daran, etwas zu erschaffen! Auf der Grundlage von Scratch bietet Pyonkee eine echte Programmierumgebung – immer und überall.
> 
> Pyonkee ist ein neues dynamisches Medium, um eine breite Palette von Ideen zu verwirklichen. Durch das Zusammensetzen visueller Blöcke können Kinder wie auch Erwachsene eigene Spiele, Animationen und Geschichten erstellen. Der Programmiervorgang fördert und vermittelt Logik, Produktivität, Kreativität und Zusammenarbeit.
> 
> Pyonkee wurde unter Verwendung des Open-Source-Quellcodes von „Scratch 1.4“ des MIT Media Lab entwickelt. Dadurch ist Pyonkee vollständig kompatibel zu Scratch 1.4, sodass sich einige millionen bestehender Scratch-Projekte als Grundlage und Anregung verwenden lassen.
> 
> Die Oberfläche von Pyonkee wurde für die Touch-Bedienung optimiert und verzichtet auf langwierige Texteingaben oder Maus-Schubsereien. Erstelle Programme an jedem beliebigen Ort! Pyonkee unterstützt das Zoomen durch Spreizgesten und die Anpassung der Schriftgröße für kleine Bildschirme. Zudem ist ein Sound-Rekorder und und eine Kamera-Unterstützung integriert, damit du eigene Klänge und Fotos in deine Projekte einfügen kannst. Mit Pyonkee kannst du unterschiedliche Medien verknüpfen und programmgesteuert nutzen.
> 
> Deine Projekte kannst du über AirDrop, E-Mail, iCloud und Dropbox teilen. Seit der Version 2.1 ist es möglich, verschiedene iPad-Sensoren in Programmen zu nutzen und über ein Mesh-Netzwerk-Protokoll beliebige Ereignisse und Variablenwerte mit Anderen zu teilen. Ab Version 2.3 stehen bei den „Klänge“-Blöcken mehr als 100 Instrumente zur Auswahl. Durch das Aktivieren von „Virtual MIDI“ in den iOS-Einstellungen für Pyonkee ist es sogar möglich, die Klänge anderer Synth-Apps abzuspielen.
> 
> Stürz‘ dich in den Spaß der visuellen Programmierung! 

I did not translate the "What's New" / "Version History" part yet. There are some apps on the german App Store that do not provide a german translation of the release notes (like Prezi Viewer) and many who do. I saw the french version provides a translation since V2.1 .  Being a teacher for computer science and physics I do not know the correct technical terms for the sound blocks and I am not able to derive them from the given block labels. If you would like to have a correct german translation of the 2.6 Version History I will ask a colleague next week.

**Comment by mumez** [comment]
Great! I think the translation of the main description is just enough for the most users.
I will include your contributions to the next (2.7) version of Pyonkee, which will be released in May.
Thank you again!

**Comment by mumez** [comment]
Pyonkee 2.7 has been released on App Store. https://itunes.apple.com/de/app/pyonkee/id905012686
I'll update README for your contribution. Thanks!
